server:
  port: 9091
spring:
  config:
    import: "optional:configserver:"

  application:
    name: dataIn-eureka-server
  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: dataIn-config-server
#Eureka Standalone Server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
